[package]
name = "aion_kernel"
version = "0.1.0"
edition = "2021"
description = "AION OS Bare-Metal Microkernel. The foundation of the global DePIN supercomputer."

[dependencies]
# Dependências agnósticas de plataforma podem ir aqui

[target.'cfg(target_arch = "x86_64")'.dependencies]
bootloader = "0.9"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
