# Enable AndroidX support
android.useAndroidX=true

# Kotlin style
kotlin.code.style=official

# JVM memory configuration
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Android non-transitive R classes
android.nonTransitiveRClass=true

# Force Gradle to use AS JDK
org.gradle.java.home=C\:/Program Files/Android/Android Studio/jbr
org.gradle.configuration-cache=false

# Revert experimental DSL settings to stable defaults
# android.newDsl=false
# android.defaults.buildfeatures.resvalues=true
