# Enable AndroidX support
android.useAndroidX=true

# Kotlin style
kotlin.code.style=official

# JVM memory configuration for Gradle & NDK compilation
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Android non-transitive R classes for build speed optimization
android.nonTransitiveRClass=true
