# Enable AndroidX support
android.useAndroidX=true

# Kotlin style
kotlin.code.style=official

# JVM memory configuration for Gradle & NDK compilation
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Android non-transitive R classes for build speed optimization
android.nonTransitiveRClass=true

# Force Gradle to use Android Studio's bundled JDK to avoid Java 25 conflicts
org.gradle.java.home=C\:/Program Files/Android/Android Studio/jbr
org.gradle.configuration-cache=true
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
